name: Build and Push Artifact to JFrog

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v5
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_TOKEN }}

      - name: Build artifact
        run: |
          mkdir build
          echo "This is my build from GitHub Actions" > build/app.txt
          zip -r app-build.zip build/

      - name: Upload artifact to JFrog
        run: |
          jf rt upload "app-build.zip" "generic-local/github-actions/app-build-${{ github.run_number }}.zip"

      - name: Publish build info
        run: |
          jf rt build-publish github-actions-build ${{ github.run_number }}
