name: Upload Generic Build to JFrog

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Create build artifact
        run: |
          mkdir -p build
          cp app.txt build/
          zip -r app-build.zip build README.md

      - name: Upload artifact to JFrog Generic Repository
        run: |
          curl -u "${{ secrets.JF_USER }}:${{ secrets.JF_TOKEN }}" \
            -T app-build.zip \
            "${{ secrets.JF_URL }}/generic-local/github-actions/app-build-${{ github.run_number }}.zip"
